version: '3'

services:
  intro-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '15432:5432'
    volumes:
      - /Users/helissonnas/dataPlace:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  intro-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '16543:80'
    depends_on:
      - intro-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
